PCI: label: Fix compilation error when CONFIG_ACPI is unset
This patch fixes compilation error descibed below introduced by
the commit 6fe085cb0946d15226fcd581a4f40853f06c4443

drivers/pci/pci-label.c: In function ‘pci_create_firmware_label_files’:
drivers/pci/pci-label.c:366:2: error: implicit declaration of function ‘device_has_dsm’

Signed-off-by: Narendra K <narendra_k@dell.com>
Signed-off-by: Jesse Barnes <jbarnes@virtuousgeek.org>