[ARM] 4530/1: MXC: fix elf_hwcap compile breakage as in iop13xx
MXC needs the same change as IOP.  See [ARM] 4494/1
or commit 22d72d0d58044c76034af2f21a63168c0d46fa12

An undefined reference to elf_hwcap prevents linkage, due
to changes made by da55f546e2ff3cd18ed632ab213fc10cc9407ce7
and d7edc338d83c1c18a5c5b4551dc08dd9868a7a7e

Removing processor.h removes the extern definition of
elf_hwcap, which fixes the link issue, but forgets cpu_relax().
So, instead, we'll call barrier() directly.

Cc: Lennert Buytenhek <kernel@wantstofly.org>
Cc: Catalin Marinas <catalin.marinas@arm.com>
Acked-by: Ross Wille <wille@freescale.com>
Signed-off-by: Quinn Jensen <quinn.jensen@freescale.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>