ASoC: Fix build error in twl4030.c
Fix the (likely cut-n-paste) error by commit
663e76034365a3e2f63a651ca986622e68b370d8, which causes the error below:
  sound/soc/codecs/twl4030.c: In function 'twl4030_read_reg_cache':
  sound/soc/codecs/twl4030.c:152: error: 'cache' undeclared (first use in this function)

Signed-off-by: Takashi Iwai <tiwai@suse.de>