mtd: mxc_nand: Remove duplicate NAND_CMD_RESET case value
This reverts commit 07485cb2 ("mtd: mxc_nand: add RESET command support").
Support for NAND_CMD_RESET was added separately in commit 33091f99
("mtd: mxc_nand: set NFC registers after reset"), causing a build error:

drivers/mtd/nand/mxc_nand.c: In function 'mxc_nand_command':
drivers/mtd/nand/mxc_nand.c:689: error: duplicate case value
drivers/mtd/nand/mxc_nand.c:606: error: previously used here

Signed-off-by: David Woodhouse <David.Woodhouse@intel.com>