Revert "[SCSI] cnic: fix error: implicit declaration of function ‘__symbol_get’"
This reverts commit 624783a2f1f2a49fa80cc553e407959c681fe721.

All the commit did was add a second #include of <linux/module.h> which is
the wrong fix.

Signed-off-by: James Bottomley <James.Bottomley@HansenPartnership.com>