[PATCH] net: ne2k.c won't compile if pci_clone_list is const
net: ne2k.c won't compile if pci_clone_list is const

d34c41c522c7703b2759f396e15f29b813df5d53 which (amongst other things)
made pci_clone_list in ne2k-pci.c const causes the following compile error.
This patch reverses that portion of that changeset

drivers/net/ne2k-pci.c:123: error: pci_clone_list causes a section type
conflict

~/ gcc --version
gcc (GCC) 4.0.3 (Debian 4.0.3-1)
~/ dpkg gcc-4.0 | grep Version
Version: 4.0.3-1

Signed-Off-By: Horms <horms@verge.net.au

 ne2k-pci.c |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

cee0890cc97247b6a9decd94f5dc0719ac8f0b1b

Signed-off-by: Jeff Garzik <jeff@garzik.org>