net: fix driver build errors due to missing net/ip6_checksum.h include
  2.6.27-git2 kernel build fails with allyesconfig on powerpc with 
build error 

<introduced by commit 8fce48347e17a61bb3d197635fa9c2464798d409> 

CC    drivers/net/enic/enic_main.o
drivers/net/enic/enic_main.c: In function âenic_queue_wq_skb_tsoâ:
drivers/net/enic/enic_main.c:576: error: implicit declaration of function âcsum_ipv6_magicâ
make[3]: *** [drivers/net/enic/enic_main.o] Error 1

<introduced by commit 18fe2e1898c8a0a89bb472fb2ad479cff986e450>

drivers/net/qlge/qlge_main.c: In function âql_tsoâ:
drivers/net/qlge/qlge_main.c:1862: error: implicit declaration of function âcsum_ipv6_magicâ
make[3]: *** [drivers/net/qlge/qlge_main.o] Error 1
  
<introduced by commit cd89e6810517fbb93e0f7e19d72b8ad2dfefd25b>

drivers/net/jme.c: In function âjme_tx_tsoâ:
drivers/net/jme.c:1784: error: implicit declaration of function âcsum_ipv6_magicâ
make[2]: *** [drivers/net/jme.o] Error 1

Signed-off-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>
Signed-off-by: Ron Mercer <ron.mercer@qlogic.com>
Signed-off-by: David S. Miller <davem@davemloft.net>